general {
    lock_cmd = ~/.config/hypr/scripts/start-hyprlock
    unlock_cmd = true
    after_sleep_cmd = ~/.config/hypr/scripts/restore-dpms
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
